export type AppLang = 'tr' | 'en';

export function resolveLang(input?: string | null): AppLang {
  return String(input ?? 'tr').toLowerCase().startsWith('en') ? 'en' : 'tr';
}

export const copy = {
  tr: {
    appName: 'Yeedoy Karekod Menu',
    heroKicker: 'Canli dijital menu',
    publicMenu: 'Acik Menu',
    searchPlaceholder: 'Menude ara',
    allCategories: 'Tum kategoriler',
    featuredItems: 'One cikanlar',
    filters: 'Filtreler',
    clearFilters: 'Filtreleri temizle',
    themeMode: 'Marka modu',
    languageMode: 'Dil',
    languageTr: 'Turkce',
    languageEn: 'English',
    resultsCount: 'Gorunen urun',
    categoryJump: 'Kategori gecisi',
    themePreview: 'Tema gorunumu',
    curatedSelection: 'Secili imza tabaklar',
    heroSummary: 'Kategori, urun ve link odakli hizli menu deneyimi',
    openDetails: 'Detayi ac',
    copySuccess: 'Link kopyalandi',
    premiumQrHint: 'QR ciktilari marka sunumu icin hazirlandi.',
    closeDetails: 'Detay panelini kapat',
    unavailable: 'Musait degil',
    soldOut: 'Tukendi',
    noResultsTitle: 'Bu filtreyle eslesen urun bulunamadi',
    noResultsBody: 'Aramayi temizleyin ya da baska bir kategori secin.',
    category: 'Kategori',
    details: 'Detay',
    variants: 'Secenekler',
    tags: 'Etiketler',
    photos: 'Fotograflar',
    priceHistory: 'Fiyat gecmisi',
    close: 'Kapat',
    qrTitle: 'Karekod Menu Olustur',
    qrDescription:
      'Bu sayfa yalnizca public menu linki ve QR ciktisi uretir. Isletme CRUD islemleri panelde kalir.',
    canonicalLink: 'Acik menu baglantisi',
    shortLink: 'Kisa baglanti',
    copyLink: 'Linki kopyala',
    downloadPng: 'PNG indir',
    downloadSvg: 'SVG indir',
    colorVariant: 'Renk varyasyonu',
    includeLogo: 'Logo goster',
    categoryView: 'Kategori',
    itemView: 'Urun',
    pageView: 'Menu',
    allItems: 'Tum urunler',
    menuUpdated: 'Menu guncellendi',
    menuSections: 'Menu bolumleri',
    generatedFor: 'Hazirlanan QR',
    backToMenu: 'Menuye don',
    routeHint: 'Yol yapisi businessId uzerinden calisir.',
    notFoundTitle: 'Menu bulunamadi',
    notFoundBody: 'Bu isletme icin yayinlanmis bir menu veya gecerli bir baglanti bulunamadi.',
    goHome: 'Ana sayfa',
    feedbackTitle: 'Bu menu hakkinda ne dusunuyorsunuz?',
    feedbackCategory: 'Konu',
    feedbackCategoryMenu: 'Menu icerigi',
    feedbackCategoryPrice: 'Fiyatlar',
    feedbackCategoryService: 'Servis',
    feedbackCategoryApp: 'Uygulama',
    feedbackCategoryOther: 'Diger',
    feedbackMessage: 'Yorumunuz (opsiyonel)',
    feedbackSubmit: 'Gonder',
    feedbackSuccess: 'Geri bildiriminiz alindi, tesekkurler!',
    feedbackError: 'Bir sorun olustu, lutfen tekrar deneyin.',
    feedbackButtonLabel: 'Geri Bildirim',
    openNow: 'Su an acik',
    closedNow: 'Simdi kapali',
    breadcrumbDiscover: 'Kesfet',
    breadcrumbRestaurants: 'Restoranlar',
    breadcrumbMenu: 'Menu',
    favoriteButton: 'Favori',
    favoriteButtonAria: 'Favorilere ekle',
    shareButton: 'Paylas',
    shareButtonAria: 'Paylas',
    reserveTableButton: 'Masa Ayirt',
    menuCategoriesTitle: 'Menu Kategorileri',
    featuredCategoryLabel: 'One Cikanlar',
    promoBannerTitle: 'Lezzetli firsatlar seni bekliyor!',
    promoBannerBody: 'En iyi kampanyalari kacirma.',
    showMoreButton: 'Daha fazla goster',
    noSearchResultsPrefix: '',
    noSearchResultsSuffix: 'icin sonuc bulunamadi',
    noSearchResultsHint: 'Farkli bir arama terimi deneyin',
    verifiedBusinessLabel: 'Dogrulanmis Isletme',
    priceOnRequest: 'Fiyata sorunuz',
    allergenPrefix: 'Alerjen',
    featuredItemsSubtitle: 'En cok tercih edilen lezzetler',
  },
  en: {
    appName: 'Yeedoy Karekod Menu',
    heroKicker: 'Live digital menu',
    publicMenu: 'Public Menu',
    searchPlaceholder: 'Search the menu',
    allCategories: 'All categories',
    featuredItems: 'Featured',
    filters: 'Filters',
    clearFilters: 'Clear filters',
    themeMode: 'Brand mode',
    languageMode: 'Language',
    languageTr: 'Turkish',
    languageEn: 'English',
    resultsCount: 'Visible items',
    categoryJump: 'Category jump',
    themePreview: 'Theme preview',
    curatedSelection: 'Curated signature picks',
    heroSummary: 'Fast menu reading focused on categories, items and shareable links',
    openDetails: 'Open details',
    copySuccess: 'Link copied',
    premiumQrHint: 'QR assets are prepared for branded presentation.',
    closeDetails: 'Close detail sheet',
    unavailable: 'Unavailable',
    soldOut: 'Sold out',
    noResultsTitle: 'No items match this filter',
    noResultsBody: 'Clear the search or choose another category.',
    category: 'Category',
    details: 'Details',
    variants: 'Variants',
    tags: 'Tags',
    photos: 'Photos',
    priceHistory: 'Price history',
    close: 'Close',
    qrTitle: 'Generate QR Menu',
    qrDescription:
      'This page only produces the public menu link and QR assets. Business CRUD remains in the separate panel.',
    canonicalLink: 'Public menu link',
    shortLink: 'Short link',
    copyLink: 'Copy link',
    downloadPng: 'Download PNG',
    downloadSvg: 'Download SVG',
    colorVariant: 'Color variant',
    includeLogo: 'Show logo',
    categoryView: 'Category',
    itemView: 'Item',
    pageView: 'Menu',
    allItems: 'All items',
    menuUpdated: 'Menu updated',
    menuSections: 'Menu sections',
    generatedFor: 'QR prepared for',
    backToMenu: 'Back to menu',
    routeHint: 'Routes are keyed by businessId.',
    notFoundTitle: 'Menu not found',
    notFoundBody: 'No published menu or valid link was found for this business.',
    goHome: 'Home',
    feedbackTitle: 'What do you think about this menu?',
    feedbackCategory: 'Topic',
    feedbackCategoryMenu: 'Menu content',
    feedbackCategoryPrice: 'Prices',
    feedbackCategoryService: 'Service',
    feedbackCategoryApp: 'App',
    feedbackCategoryOther: 'Other',
    feedbackMessage: 'Your comment (optional)',
    feedbackSubmit: 'Send',
    feedbackSuccess: 'Thank you for your feedback!',
    feedbackError: 'Something went wrong, please try again.',
    feedbackButtonLabel: 'Feedback',
    openNow: 'Open now',
    closedNow: 'Closed now',
    breadcrumbDiscover: 'Discover',
    breadcrumbRestaurants: 'Restaurants',
    breadcrumbMenu: 'Menu',
    favoriteButton: 'Favorite',
    favoriteButtonAria: 'Add to favorites',
    shareButton: 'Share',
    shareButtonAria: 'Share',
    reserveTableButton: 'Reserve a Table',
    menuCategoriesTitle: 'Menu Categories',
    featuredCategoryLabel: 'Featured',
    promoBannerTitle: 'Tasty deals are waiting for you!',
    promoBannerBody: "Don't miss the best offers.",
    showMoreButton: 'Show more',
    noSearchResultsPrefix: 'No results for',
    noSearchResultsSuffix: '',
    noSearchResultsHint: 'Try a different search term',
    verifiedBusinessLabel: 'Verified Business',
    priceOnRequest: 'Price on request',
    allergenPrefix: 'Allergen',
    featuredItemsSubtitle: 'Most popular picks',
  },
} as const;

export type MenuCopy = (typeof copy)[AppLang];

export const allergenLabels = {
  tr: {
    gluten: 'Gluten',
    milk: 'Süt',
    eggs: 'Yumurta',
    fish: 'Balık',
    shellfish: 'Kabuklu',
    peanuts: 'Yer Fıstığı',
    treenuts: 'Kuruyemiş',
    soy: 'Soya',
    celery: 'Kereviz',
    mustard: 'Hardal',
    sesame: 'Susam',
    sulphites: 'Sülfitler',
    lupin: 'Acı Bakla',
    molluscs: 'Yumuşakça',
  },
  en: {
    gluten: 'Gluten',
    milk: 'Milk',
    eggs: 'Eggs',
    fish: 'Fish',
    shellfish: 'Shellfish',
    peanuts: 'Peanuts',
    treenuts: 'Tree Nuts',
    soy: 'Soy',
    celery: 'Celery',
    mustard: 'Mustard',
    sesame: 'Sesame',
    sulphites: 'Sulphites',
    lupin: 'Lupin',
    molluscs: 'Molluscs',
  },
} as const;
