// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94CHuacYVfpy9haM-ryxTqLcd10IdQRE',
    appId: '1:772285544200:web:181f37c1102a5334a95ebd',
    messagingSenderId: '772285544200',
    projectId: 'yeedoy-8cd31',
    authDomain: 'yeedoy-8cd31.firebaseapp.com',
    storageBucket: 'yeedoy-8cd31.firebasestorage.app',
    measurementId: 'G-K84FZWLXPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALRxIBw1NgnnYoHeIjWiHF0Ob1TESDw38',
    appId: '1:772285544200:android:9c28c693c3950a86a95ebd',
    messagingSenderId: '772285544200',
    projectId: 'yeedoy-8cd31',
    storageBucket: 'yeedoy-8cd31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_60FZFb5CVwnMkoA_9937cNZ7xKkf04',
    appId: '1:772285544200:ios:96746f1f6a33c693a95ebd',
    messagingSenderId: '772285544200',
    projectId: 'yeedoy-8cd31',
    storageBucket: 'yeedoy-8cd31.firebasestorage.app',
    iosBundleId: 'com.yeedoy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_60FZFb5CVwnMkoA_9937cNZ7xKkf04',
    appId: '1:772285544200:ios:96746f1f6a33c693a95ebd',
    messagingSenderId: '772285544200',
    projectId: 'yeedoy-8cd31',
    storageBucket: 'yeedoy-8cd31.firebasestorage.app',
    iosBundleId: 'com.yeedoy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA94CHuacYVfpy9haM-ryxTqLcd10IdQRE',
    appId: '1:772285544200:web:5900b3e4225f21e2a95ebd',
    messagingSenderId: '772285544200',
    projectId: 'yeedoy-8cd31',
    authDomain: 'yeedoy-8cd31.firebaseapp.com',
    storageBucket: 'yeedoy-8cd31.firebasestorage.app',
    measurementId: 'G-9X0NJJYC64',
  );
}

