-- 117 mevcut stok görselinin (varsayilan-yemek-gorseli.ts / varsayilan_yemek_sozlugu.dart
-- statik sözlüklerinden taşınan) stock_dish_images tablosuna ilk yükleme migration'ı.
-- Dosyalar Supabase Storage'da (menu-media/varsayilan-yemekler/...) zaten duruyor,
-- yeniden yüklenmiyor — sadece katalog satırı olarak kaydediliyor.
INSERT INTO public.stock_dish_images (image_url, keywords) VALUES
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/anali_kizli.webp', ARRAY['anali kizli']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/arabasi.webp', ARRAY['arabasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/ayak_paca.webp', ARRAY['ayak paca']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/balik.webp', ARRAY['balik']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/bamya.webp', ARRAY['bamya corbasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/beyran.webp', ARRAY['beyran']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/brokoli.webp', ARRAY['brokoli']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/dil_paca.webp', ARRAY['dil paca']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/domates.webp', ARRAY['domates']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/dugun.webp', ARRAY['dugun']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/ezogelin.webp', ARRAY['ezogelin']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/iskembe.webp', ARRAY['iskembe']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/kelle_paca.webp', ARRAY['kelle paca']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/kofte.webp', ARRAY['kofte']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/lebeniye.webp', ARRAY['lebeniye']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/mahluta.webp', ARRAY['mahluta']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/mantar.webp', ARRAY['mantar']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/maras_tarhanasi.webp', ARRAY['maras tarhanasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/mercimek.webp', ARRAY['mercimek']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/paca.webp', ARRAY['paca']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/sehriye.webp', ARRAY['sehriye']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/siveydiz.webp', ARRAY['siveydiz']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/tarhana.webp', ARRAY['tarhana']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/tavuk_suyu.webp', ARRAY['tavuk suyu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/tuzlama.webp', ARRAY['tuzlama']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/yayla.webp', ARRAY['yayla']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/corbalar/yogurtlu.webp', ARRAY['yogurtlu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/acili_ezme.webp', ARRAY['acili ezme']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/atom.webp', ARRAY['atom']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/babagannus.webp', ARRAY['babagannus']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/cacik.webp', ARRAY['cacik']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/coban.webp', ARRAY['coban']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/deniz_borulcesi.webp', ARRAY['deniz borulcesi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/enginar.webp', ARRAY['enginar salatasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/fava.webp', ARRAY['fava']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/gavurdagi.webp', ARRAY['gavurdagi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/haydari.webp', ARRAY['haydari']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/humus.webp', ARRAY['humus']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/kopoglu.webp', ARRAY['kopoglu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/koz_biber.webp', ARRAY['koz biber']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/kozlenmis_patlican.webp', ARRAY['kozlenmis patlican']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/kisir.webp', ARRAY['kisir']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/lahana.webp', ARRAY['lahana']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/mevsim.webp', ARRAY['mevsim']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/muhammara.webp', ARRAY['muhammara']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/pancar.webp', ARRAY['pancar']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/patates.webp', ARRAY['patates']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/piyaz.webp', ARRAY['piyaz']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/roka.webp', ARRAY['roka']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/saksuka.webp', ARRAY['saksuka']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/sezar.webp', ARRAY['sezar']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/tarator.webp', ARRAY['tarator']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/ton_balikli.webp', ARRAY['ton balikli']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/tursu.webp', ARRAY['tursu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/yesil.webp', ARRAY['yesil']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/yogurtlu_semizotu.webp', ARRAY['yogurtlu semizotu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/salata-meze/zeytinyagli_barbunya.webp', ARRAY['zeytinyagli barbunya']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/ali_nazik.webp', ARRAY['ali nazik']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/bamya.webp', ARRAY['etli bamya']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/bezelye_etli.webp', ARRAY['bezelye etli']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/coban_kavurma.webp', ARRAY['coban kavurma']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/dana_haslama.webp', ARRAY['dana haslama']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/eksili_kofte.webp', ARRAY['eksili kofte']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/et_sote.webp', ARRAY['et sote']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/etli_guvec.webp', ARRAY['etli guvec']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/etli_lahana.webp', ARRAY['etli lahana']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/etli_nohut.webp', ARRAY['etli nohut']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/etli_patates.webp', ARRAY['etli patates']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/hunkar_begendi.webp', ARRAY['hunkar begendi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/islim_kebabi.webp', ARRAY['islim kebabi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/ispanak.webp', ARRAY['ispanak']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/izmir_kofte.webp', ARRAY['izmir kofte']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/kabak.webp', ARRAY['kabak yemegi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/kabak_oturtma.webp', ARRAY['kabak oturtma']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/kapuska.webp', ARRAY['kapuska']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/karni_yarik.webp', ARRAY['karni yarik']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/kereviz.webp', ARRAY['kereviz yemegi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/kuru_fasulye.webp', ARRAY['kuru fasulye']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/musakka.webp', ARRAY['musakka']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/nohut.webp', ARRAY['nohut']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/orman_kebabi.webp', ARRAY['orman kebabi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/patates_oturtma.webp', ARRAY['patates oturtma']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/patlican_kebabi.webp', ARRAY['patlican kebabi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/pilav_ustu_kuru.webp', ARRAY['pilav ustu kuru']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/pirasa.webp', ARRAY['pirasa yemegi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/sac_kavurma.webp', ARRAY['sac kavurma']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/sebzeli_guvec.webp', ARRAY['sebzeli guvec']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/sulu_kofte.webp', ARRAY['sulu kofte']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/tas_kebabi.webp', ARRAY['tas kebabi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/tavuk_haslama.webp', ARRAY['tavuk haslama']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/tavuk_sote.webp', ARRAY['tavuk sote']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/tavuk_yahni.webp', ARRAY['tavuk yahni']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/taze_fasulye.webp', ARRAY['taze fasulye yemegi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/terbiyeli_kofte.webp', ARRAY['terbiyeli kofte']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/turlu.webp', ARRAY['turlu']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/sulu_yemekler/yumurtali_ispanak.webp', ARRAY['yumurtali ispanak']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/bakla.webp', ARRAY['bakla']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/bamya.webp', ARRAY['zeytinyagli bamya']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/barbunya.webp', ARRAY['barbunya']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/bezelye.webp', ARRAY['bezelye']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/biber_dolmasi.webp', ARRAY['biber dolmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/biber_kizartmasi.webp', ARRAY['biber kizartmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/borulce.webp', ARRAY['borulce']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/bruksel_lahanasi.webp', ARRAY['bruksel lahanasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/enginar.webp', ARRAY['zeytinyagli enginar']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/imam_bayildi.webp', ARRAY['imam bayildi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/kabak.webp', ARRAY['zeytinyagli kabak']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/kabak_dolmasi.webp', ARRAY['kabak dolmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/kabak_kizartmasi.webp', ARRAY['kabak kizartmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/karniyarik.webp', ARRAY['karniyarik']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/kereviz.webp', ARRAY['zeytinyagli kereviz']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/lahana_sarma.webp', ARRAY['lahana sarma']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/patlican_dolmasi.webp', ARRAY['patlican dolmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/patlican_kizartmasi.webp', ARRAY['patlican kizartmasi']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/pirasa.webp', ARRAY['zeytinyagli pirasa']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/taze_fasulye.webp', ARRAY['zeytinyagli taze fasulye']::text[]),
  ('https://dktdnbeougrmhkzplbap.supabase.co/storage/v1/object/public/menu-media/varsayilan-yemekler/zeytinyaglilar/yaprak_sarma.webp', ARRAY['yaprak sarma']::text[])
ON CONFLICT DO NOTHING;
