// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PtUajx9_VwD6FIIqwUyx34Bc17Pjxxk',
    appId: '1:123993913288:web:c1cb44a219d887d434f2fd',
    messagingSenderId: '123993913288',
    projectId: 'yeedoy-f81c8',
    authDomain: 'yeedoy-f81c8.firebaseapp.com',
    storageBucket: 'yeedoy-f81c8.firebasestorage.app',
    measurementId: 'G-G7T2LELK0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GiWZoq5G14G6njwWKrfVZkOnPnErywE',
    appId: '1:123993913288:android:1d474cd3807c080e34f2fd',
    messagingSenderId: '123993913288',
    projectId: 'yeedoy-f81c8',
    storageBucket: 'yeedoy-f81c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39uX0JmUw0kqjaCuEE4GYAGMou6Fwv9I',
    appId: '1:123993913288:ios:2e45ae1e36f37c3c34f2fd',
    messagingSenderId: '123993913288',
    projectId: 'yeedoy-f81c8',
    storageBucket: 'yeedoy-f81c8.firebasestorage.app',
    iosBundleId: 'com.yeedoy.yeedoyPersonel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39uX0JmUw0kqjaCuEE4GYAGMou6Fwv9I',
    appId: '1:123993913288:ios:2e45ae1e36f37c3c34f2fd',
    messagingSenderId: '123993913288',
    projectId: 'yeedoy-f81c8',
    storageBucket: 'yeedoy-f81c8.firebasestorage.app',
    iosBundleId: 'com.yeedoy.yeedoyPersonel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PtUajx9_VwD6FIIqwUyx34Bc17Pjxxk',
    appId: '1:123993913288:web:4383e058b2bd692e34f2fd',
    messagingSenderId: '123993913288',
    projectId: 'yeedoy-f81c8',
    authDomain: 'yeedoy-f81c8.firebaseapp.com',
    storageBucket: 'yeedoy-f81c8.firebasestorage.app',
    measurementId: 'G-0YQCH01FK3',
  );
}
